server:
  port: 9003

spring:
  application:
    name: bitlog-file-service
  config:
    import:
      - nacos:bitlog-shared.yaml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

storage:
  endpoint: ${STORAGE_ENDPOINT:http://minio:9000}
  access-key: ${STORAGE_ACCESS_KEY:admin}
  secret-key: ${STORAGE_SECRET_KEY:}
  bucket: ${STORAGE_BUCKET:media}
  public-url: ${STORAGE_PUBLIC_URL:http://localhost:8001/files}

app:
  exception:
    print-stack-trace: true
