-- ============================================================
-- BitLog 初始 schema
-- ============================================================

-- update_time 由触发器统一维护，应用层无需赋值
CREATE FUNCTION touch_update_time() RETURNS trigger AS $$
BEGIN
    NEW.update_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ---------- 用户账号表 ----------
CREATE TABLE user_account
(
    id          bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username    varchar(16) NOT NULL,
    password    varchar(60),
    email       varchar(128),
    status      smallint    NOT NULL DEFAULT 1,
    user_role   smallint    NOT NULL DEFAULT 0,
    deleted     smallint    NOT NULL DEFAULT 0,
    create_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

COMMENT ON TABLE user_account IS '用户账号表';
COMMENT ON COLUMN user_account.id IS '主键ID';
COMMENT ON COLUMN user_account.username IS '用户名，唯一且可修改的公开展示名';
COMMENT ON COLUMN user_account.password IS '密码，BCrypt 加密；第三方登录用户为空';
COMMENT ON COLUMN user_account.email IS '登录邮箱，统一小写存储';
COMMENT ON COLUMN user_account.status IS '账号状态：0-禁用，1-启用';
COMMENT ON COLUMN user_account.user_role IS '角色：0-普通用户，1-管理员';
COMMENT ON COLUMN user_account.deleted IS '删除标记：0-正常，1-已删除';

-- 注销记录退出唯一性判定，原始 username/email 得以原样保留供审计
CREATE UNIQUE INDEX uk_user_account_username ON user_account (username) WHERE deleted = 0;
CREATE UNIQUE INDEX uk_user_account_email ON user_account (email) WHERE deleted = 0;

CREATE TRIGGER trg_user_account_touch
    BEFORE UPDATE ON user_account
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 用户信息表 ----------
CREATE TABLE user_info
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint       NOT NULL,
    avatar      varchar(256) NOT NULL DEFAULT '',
    position    varchar(64)  NOT NULL DEFAULT '',
    company     varchar(64)  NOT NULL DEFAULT '',
    profile     varchar(500) NOT NULL DEFAULT '',
    deleted     smallint     NOT NULL DEFAULT 0,
    create_time timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_info_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_info_user FOREIGN KEY (user_id) REFERENCES user_account (id)
);

COMMENT ON TABLE user_info IS '用户信息表';
COMMENT ON COLUMN user_info.id IS '主键ID';
COMMENT ON COLUMN user_info.user_id IS '所属账号';
COMMENT ON COLUMN user_info.avatar IS '头像 URL';
COMMENT ON COLUMN user_info.position IS '职位';
COMMENT ON COLUMN user_info.company IS '公司';
COMMENT ON COLUMN user_info.profile IS '个人简介';
COMMENT ON COLUMN user_info.deleted IS '删除标记：0-正常，1-已删除';

CREATE TRIGGER trg_user_info_touch
    BEFORE UPDATE ON user_info
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 标签表 ----------
CREATE TABLE tag
(
    id          bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(64) NOT NULL,
    create_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

COMMENT ON TABLE tag IS '标签表';
COMMENT ON COLUMN tag.id IS '主键ID';
COMMENT ON COLUMN tag.name IS '标签名称';

CREATE TRIGGER trg_tag_touch
    BEFORE UPDATE ON tag
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 文章分类表 ----------
CREATE TABLE category
(
    id          bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(64) NOT NULL,
    create_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_category_name UNIQUE (name)
);

COMMENT ON TABLE category IS '文章分类表';
COMMENT ON COLUMN category.id IS '主键ID';
COMMENT ON COLUMN category.name IS '分类名称';

CREATE TRIGGER trg_category_touch
    BEFORE UPDATE ON category
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 文章主表 ----------
CREATE TABLE article
(
    id                   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id              bigint       NOT NULL,
    category_id          bigint,
    latest_version_id    bigint,
    published_version_id bigint,
    publish_time         timestamptz,
    summary              varchar(512) NOT NULL DEFAULT '',
    version_count        integer      NOT NULL DEFAULT 0,
    deleted              smallint     NOT NULL DEFAULT 0,
    create_time          timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time          timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_article_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES category (id)
);

COMMENT ON TABLE article IS '文章主表';
COMMENT ON COLUMN article.id IS '主键ID';
COMMENT ON COLUMN article.user_id IS '作者';
COMMENT ON COLUMN article.category_id IS '分类，NULL 表示未归类';
COMMENT ON COLUMN article.latest_version_id IS '最新版本';
COMMENT ON COLUMN article.published_version_id IS '已发布版本，NULL 表示未发布';
COMMENT ON COLUMN article.publish_time IS '首次发布时间，NULL 表示从未发布';
COMMENT ON COLUMN article.summary IS '文章摘要';
COMMENT ON COLUMN article.version_count IS '版本总数';
COMMENT ON COLUMN article.deleted IS '是否删除：0-未删除，1-已删除';

CREATE INDEX idx_article_user_id ON article (user_id);
CREATE INDEX idx_article_category_id ON article (category_id);
CREATE INDEX idx_article_published_version_id ON article (published_version_id);

CREATE TRIGGER trg_article_touch
    BEFORE UPDATE ON article
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 文章版本表（只追加） ----------
CREATE TABLE article_version
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    article_id  bigint       NOT NULL,
    version     integer      NOT NULL DEFAULT 1,
    title       varchar(200) NOT NULL DEFAULT '',
    content     text         NOT NULL,
    create_time timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_article_version UNIQUE (article_id, version),
    CONSTRAINT fk_article_version_article FOREIGN KEY (article_id) REFERENCES article (id)
);

COMMENT ON TABLE article_version IS '文章版本表（只追加）';
COMMENT ON COLUMN article_version.id IS '主键ID';
COMMENT ON COLUMN article_version.article_id IS '所属文章';
COMMENT ON COLUMN article_version.version IS '版本号';
COMMENT ON COLUMN article_version.title IS '文章标题';
COMMENT ON COLUMN article_version.content IS '文章内容';

CREATE INDEX idx_article_version_article_id ON article_version (article_id);

-- article 的版本指针与 article_version 互相引用，建表期先跳过，待两表就绪后补上
ALTER TABLE article
    ADD CONSTRAINT fk_article_latest_version
        FOREIGN KEY (latest_version_id) REFERENCES article_version (id),
    ADD CONSTRAINT fk_article_published_version
        FOREIGN KEY (published_version_id) REFERENCES article_version (id);


-- ---------- 文章标签关联表 ----------
CREATE TABLE article_tag
(
    id          bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    article_id  bigint      NOT NULL,
    tag_id      bigint      NOT NULL,
    create_time timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_article_tag UNIQUE (article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY (article_id) REFERENCES article (id),
    CONSTRAINT fk_article_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);

COMMENT ON TABLE article_tag IS '文章标签关联表';
COMMENT ON COLUMN article_tag.id IS '主键ID';
COMMENT ON COLUMN article_tag.article_id IS '文章';
COMMENT ON COLUMN article_tag.tag_id IS '标签';

CREATE INDEX idx_article_tag_tag_id ON article_tag (tag_id);


-- ---------- 文章统计表 ----------
CREATE TABLE article_statistics
(
    id            bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    article_id    bigint      NOT NULL,
    read_count    integer     NOT NULL DEFAULT 0,
    comment_count integer     NOT NULL DEFAULT 0,
    create_time   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_article_statistics_article_id UNIQUE (article_id),
    CONSTRAINT fk_article_statistics_article FOREIGN KEY (article_id) REFERENCES article (id)
);

COMMENT ON TABLE article_statistics IS '文章统计表';
COMMENT ON COLUMN article_statistics.id IS '主键ID';
COMMENT ON COLUMN article_statistics.article_id IS '文章';
COMMENT ON COLUMN article_statistics.read_count IS '阅读数';
COMMENT ON COLUMN article_statistics.comment_count IS '评论数';

CREATE TRIGGER trg_article_statistics_touch
    BEFORE UPDATE ON article_statistics
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 评论表 ----------
CREATE TABLE comment
(
    id               bigint        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    article_id       bigint        NOT NULL,
    user_id          bigint        NOT NULL,
    root_id          bigint,
    parent_id        bigint,
    reply_to_user_id bigint,
    content          varchar(1000) NOT NULL,
    status           smallint      NOT NULL DEFAULT 1,
    deleted          smallint      NOT NULL DEFAULT 0,
    create_time      timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_comment_article FOREIGN KEY (article_id) REFERENCES article (id),
    CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT fk_comment_root FOREIGN KEY (root_id) REFERENCES comment (id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_id) REFERENCES comment (id),
    CONSTRAINT fk_comment_reply_to_user FOREIGN KEY (reply_to_user_id) REFERENCES user_account (id)
);

COMMENT ON TABLE comment IS '评论表';
COMMENT ON COLUMN comment.id IS '主键ID';
COMMENT ON COLUMN comment.article_id IS '所属文章';
COMMENT ON COLUMN comment.user_id IS '评论者';
COMMENT ON COLUMN comment.root_id IS '根评论，NULL 表示自身即根评论';
COMMENT ON COLUMN comment.parent_id IS '父评论，NULL 表示一级评论';
COMMENT ON COLUMN comment.reply_to_user_id IS '被回复者，NULL 表示直接回复根评论';
COMMENT ON COLUMN comment.content IS '评论内容（纯文本）';
COMMENT ON COLUMN comment.status IS '状态：1-正常，2-已隐藏';
COMMENT ON COLUMN comment.deleted IS '删除标记：0-正常，1-已删除';

CREATE INDEX idx_comment_article_root_time ON comment (article_id, root_id, create_time);
CREATE INDEX idx_comment_root_time ON comment (root_id, create_time);
CREATE INDEX idx_comment_user_id ON comment (user_id);

CREATE TRIGGER trg_comment_touch
    BEFORE UPDATE ON comment
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 第三方身份关联表 ----------
CREATE TABLE user_identity
(
    id               bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id          bigint       NOT NULL,
    provider         varchar(32)  NOT NULL,
    provider_user_id varchar(128) NOT NULL,
    provider_email   varchar(128),
    create_time      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_identity_provider_uid UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_user_identity_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_user_identity_user FOREIGN KEY (user_id) REFERENCES user_account (id)
);

COMMENT ON TABLE user_identity IS '第三方身份关联表';
COMMENT ON COLUMN user_identity.id IS '主键ID';
COMMENT ON COLUMN user_identity.user_id IS '所属账号';
COMMENT ON COLUMN user_identity.provider IS '第三方平台标识：google';
COMMENT ON COLUMN user_identity.provider_user_id IS '第三方平台用户唯一ID（Google 为 sub）';
COMMENT ON COLUMN user_identity.provider_email IS '第三方平台侧邮箱，与本站登录邮箱无从属关系';

CREATE INDEX idx_user_identity_user_id ON user_identity (user_id);

CREATE TRIGGER trg_user_identity_touch
    BEFORE UPDATE ON user_identity
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();


-- ---------- 文章内容图片上传记录 ----------
CREATE TABLE image_record
(
    id          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint       NOT NULL,
    file_key    varchar(512) NOT NULL,
    deleted     smallint     NOT NULL DEFAULT 0,
    create_time timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_image_record_file_key UNIQUE (file_key),
    CONSTRAINT fk_image_record_user FOREIGN KEY (user_id) REFERENCES user_account (id)
);

COMMENT ON TABLE image_record IS '文章内容图片上传记录';
COMMENT ON COLUMN image_record.id IS '主键ID';
COMMENT ON COLUMN image_record.user_id IS '上传者';
COMMENT ON COLUMN image_record.file_key IS '文件存储Key';
COMMENT ON COLUMN image_record.deleted IS '删除标记：0-正常，1-已删除';

CREATE INDEX idx_image_record_user_id_deleted ON image_record (user_id, deleted);

CREATE TRIGGER trg_image_record_touch
    BEFORE UPDATE ON image_record
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();
