-- ============================================================
-- BitLog 友链
-- ============================================================

-- ---------- 友链表 ----------
CREATE TABLE friend_link
(
    id            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id       bigint,
    name          varchar(64)  NOT NULL,
    url           varchar(512) NOT NULL,
    avatar        varchar(512),
    description   varchar(255),
    apply_message varchar(500),
    reject_reason varchar(255),
    status        smallint     NOT NULL DEFAULT 0,
    create_time   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_friend_link_user FOREIGN KEY (user_id) REFERENCES user_account (id),
    CONSTRAINT uk_friend_link_url UNIQUE (url),
    -- 一个账号至多持有一条。站长手动录入的行 user_id 为 NULL，
    -- 而 UNIQUE 视 NULL 互不相等，这类行天然不受该约束限制。
    CONSTRAINT uk_friend_link_user UNIQUE (user_id)
);

COMMENT ON TABLE friend_link IS '友链表';
COMMENT ON COLUMN friend_link.id IS '主键ID';
COMMENT ON COLUMN friend_link.user_id IS '申请人，NULL 表示站长手动录入，无人可自助管理';
COMMENT ON COLUMN friend_link.name IS '站点名称';
COMMENT ON COLUMN friend_link.url IS '站点地址，写入前经过归一化';
COMMENT ON COLUMN friend_link.avatar IS '头像地址，审核通过后转存为自有存储';
COMMENT ON COLUMN friend_link.description IS '站点简介';
COMMENT ON COLUMN friend_link.apply_message IS '申请留言';
COMMENT ON COLUMN friend_link.reject_reason IS '拒绝理由，仅申请人本人与管理员可见';
COMMENT ON COLUMN friend_link.status IS '状态：0-待审核，1-已通过，2-已拒绝';

-- 公开列表按状态取、按加入时间倒序；id DESC 同时充当 BasePage 要求的稳定 tie-breaker
CREATE INDEX idx_friend_link_status ON friend_link (status, id DESC);

CREATE TRIGGER trg_friend_link_touch
    BEFORE UPDATE ON friend_link
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();
