-- ============================================================
-- BitLog 通知
-- ============================================================

-- ---------- 通知表 ----------
CREATE TABLE notification
(
    id             bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    recipient_id   bigint      NOT NULL,
    type           smallint    NOT NULL,
    actor_id       bigint,
    target_type    smallint    NOT NULL,
    target_id      bigint,
    dedupe_key     varchar(64),
    payload        jsonb       NOT NULL DEFAULT '{}',
    read_time      timestamptz,
    deleted        smallint    NOT NULL DEFAULT 0,
    create_time    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES user_account (id),
    CONSTRAINT fk_notification_actor FOREIGN KEY (actor_id) REFERENCES user_account (id)
    -- target_id 未建外键：它是多态引用，随 target_type 指向评论、文章或友链等不同的表，
    -- 单列外键约束不了这种指向。通知表的固有取舍，主流实现一律不加，容错靠 payload 快照。
);

COMMENT ON TABLE notification IS '通知表';
COMMENT ON COLUMN notification.id IS '主键ID';
COMMENT ON COLUMN notification.recipient_id IS '收件人，关联 user_account.id';
COMMENT ON COLUMN notification.type IS '通知类型：1-评论被回复，2-文章有新评论，3-新友链申请，4-友链审核结果，5-系统通知';
COMMENT ON COLUMN notification.actor_id IS '触发者，关联 user_account.id；系统通知为 NULL';
COMMENT ON COLUMN notification.target_type IS '目标对象类型：0-无，1-评论，2-文章，3-友链';
COMMENT ON COLUMN notification.target_id IS '目标对象 ID，随 target_type 指向不同的表；多态引用，不建外键，容错靠 payload 快照';
COMMENT ON COLUMN notification.dedupe_key IS '幂等键，由事件生产方给出；同一收件人同一键只存一条，NULL 表示不参与去重';
COMMENT ON COLUMN notification.payload IS '渲染所需的快照，避免联表查询已变化或已删除的源数据';
COMMENT ON COLUMN notification.read_time IS '已读时刻，NULL 即未读';
COMMENT ON COLUMN notification.deleted IS '删除标记：0-正常，1-已删除';

-- 列表分页：按收件人取未删除通知，按 id 倒序；覆盖最常见的通知中心列表查询
CREATE INDEX idx_notification_recipient ON notification (recipient_id, id DESC) WHERE deleted = 0;

-- 未读计数：按收件人取未读且未删除的通知
CREATE INDEX idx_notification_unread ON notification (recipient_id) WHERE read_time IS NULL AND deleted = 0;

-- 幂等键由事件生产方给出，同一收件人同一键只投递一条；NULL 表示该通知不参与去重
CREATE UNIQUE INDEX uk_notification_dedupe ON notification (recipient_id, dedupe_key) WHERE dedupe_key IS NOT NULL;

CREATE TRIGGER trg_notification_touch
    BEFORE UPDATE ON notification
    FOR EACH ROW EXECUTE FUNCTION touch_update_time();
